Udp gtpv1 sip sdp
btnt51/FisherPack-Backend pull request #18
Opened 2021-11-09 13:51 UTC by Eugene-beginning-of-the-path

2021-11-09 14:01 UTC, btnt51 requested changes
Resolve problems until 18:00 MSK 09.11.2021

2021-11-09 14:01 UTC, btnt51 commented on src/Information/Parser/ToolsForParser/Reassembly/source/UdpReassembly.cpp
> +            informReassembly.emplace_back(Service::ui16ToS(udpLayer->getUdpHeader()->length));//длина заголовка и полезной нагрузки в байтах
delete this comments, add them in .h file

2021-11-10 19:01 UTC, Alekseenkov approved these changes
you can mege

2021-11-10 19:03 UTC, btnt51 approved these changes
You can make a merge

2021-11-10 19:08 UTC, Alekseenkov requested changes
fix problems

2021-11-10 19:08 UTC, Alekseenkov commented on src/Information/Parser/ToolsForParser/Reassembly/source/UdpReassembly.cpp
> +            informReassembly.emplace_back(Service::ui16ToS(udpLayer->getUdpHeader()->headerChecksum));//проверка на ошибки заголовка и данныхПроверка на ошибки заголовка и данных
del coments in cpp

2021-11-10 19:08 UTC, Alekseenkov commented on src/Information/Parser/ToolsForParser/Reassembly/source/GtpV1Reassembly.cpp
> +            informReassembly.emplace_back(Service::ui8ToS(gtpLayer->getHeader()->extensionHeaderFlag));//1-битное значение, указывающее, есть ли необязательное поле заголовка расширения
dell coments

2021-11-11 09:01 UTC, Eugene-beginning-of-the-path commented on src/Information/Parser/ToolsForParser/Reassembly/source/UdpReassembly.cpp
> +            informReassembly.emplace_back(Service::ui16ToS(udpLayer->getUdpHeader()->headerChecksum));//проверка на ошибки заголовка и данныхПроверка на ошибки заголовка и данных
Данный комментарий уже был удален на одном из последних коммитов: https://github.com/btnt51/FisherPack-Backend/blob/UDP_GTPV1_SIP_SDP/src/Information/Parser/ToolsForParser/Reassembly/source/UdpReassembly.cpp#:~:text=informReassembly.emplace_back(Service%3A%3Aui16ToS(udpLayer-%3EgetUdpHeader()-%3EheaderChecksum))%3B

2021-11-11 09:03 UTC, Eugene-beginning-of-the-path commented on src/Information/Parser/ToolsForParser/Reassembly/source/GtpV1Reassembly.cpp
> +            informReassembly.emplace_back(Service::ui8ToS(gtpLayer->getHeader()->extensionHeaderFlag));//1-битное значение, указывающее, есть ли необязательное поле заголовка расширения
Данный комментарий уже был удален на одном из последних коммитов:
https://github.com/btnt51/FisherPack-Backend/blob/UDP_GTPV1_SIP_SDP/src/Information/Parser/ToolsForParser/Reassembly/source/GtpV1Reassembly.cpp#:~:text=informReassembly.emplace_back(Service%3A%3Aui8ToS(gtpLayer-%3EgetHeader()-%3EextensionHeaderFlag))%3B

2021-11-16 07:21 UTC, Alekseenkov approved these changes

2021-11-16 08:15 UTC, merged