ArpReassembly
btnt51/FisherPack-Backend pull request #9
Opened 2021-09-22 19:39 UTC by Eugene-beginning-of-the-path

I ask the Admin to merge this branch with the "dev" branch

2021-09-23 20:57 UTC, btnt51 requested changes
Исправь и присылай по новой

2021-09-23 20:57 UTC, btnt51 commented on src/Information/Parser/ToolsForParser/HttpReassembly/header/HttpReassembly.h
>      class HttpReassembly {
Исправить класс на namespace

2021-09-23 20:57 UTC, btnt51 commented on src/Information/Parser/ToolsForParser/HttpReassembly/header/HttpReassembly.h
>      public:
Убрать паблик

2021-09-23 20:57 UTC, btnt51 commented on src/Information/Parser/src/Parser.cpp
> +            Information::ArpReassembly::ArpReassembler(parsed_);
Исправить на return Information::ArpReassembly::ArpReassembker(parsed_);

2021-09-23 20:57 UTC, btnt51 commented on src/Service/Transformer/src/Transformer.cpp
> +    return size_tToString(temp);
Зачем тут рекурсия? Метод можно сократить до одной строчки

2021-09-23 20:57 UTC, btnt51 commented on src/Information/Loader/src/Loader.cpp
> +        //std::cout << "govno2!";
Удалить эту строчки напрочь

2021-09-23 20:57 UTC, btnt51 commented on src/Information/Loader/src/Loader.cpp
> +        //std::cout << "govno2!";
Так же исправить сам метод, в соответсвии с требованиями, которые обговаривались ранее

2021-09-23 20:57 UTC, btnt51 commented on src/Information/Parser/ToolsForParser/ArpReassembly/header/ArpReassembly.h
> +        std::vector<std::string> ArpReassembler(const pcpp::Packet& packet);
Расписать, что в каком порядке возврщается, так же поискать в разборе других слоев, на дубликацию данных (если есть, то выяснить как можно исправить, и это касается вышестоящих слоев; если эти протоколы работают на одном сетевом уровне, то дубликацию данных убирать не надо по понятным причинам.) Оформить файл в соотвествии с стильгайдом, проверить остальные слои на стильгайд и наличие коментариев в соотвествии с стильгайдом и если нет, то также исправить.

2021-09-23 20:57 UTC, btnt51 commented on src/Information/Parser/ToolsForParser/ArpReassembly/header/ArpReassembly.h
> +//#include <vector>
Почему подключаемая библиотека находится в комментарии?

2021-09-23 20:57 UTC, btnt51 commented on src/Information/Parser/ToolsForParser/ArpReassembly/header/ArpReassembly.h
> +#include <TcpReassembly.h> //?
Что означает комментарий со знаком вопроса? И при чем тут библиотека для разбора протокола TCP?

2021-09-23 20:57 UTC, btnt51 commented on src/Information/Parser/ToolsForParser/ArpReassembly/header/ArpReassembly.h
> +#ifndef FISHERPACK_BACKEND_ARPREASSEMBLY_H
Исправить ifndef в соотвествии, с тем к чему относится данные файлы. (Подсказка на будущее, на что нужно поменять: FISHERPACK_BACKEND_TOOLSFORPARSER_H), тоже самое проверить для остальных протоколов и соотвественно define и endif.

2021-09-23 20:57 UTC, btnt51 commented on src/Information/Parser/src/Parser.cpp
> +        case pcpp::ARP:
Добавить кейс для ethernet

2021-09-24 18:34 UTC, Eugene-beginning-of-the-path commented on src/Information/Parser/src/Parser.cpp
> +        case pcpp::ARP:
Кейс для Ethernet уже написан и находится самым последним в данном операторе switch.

2021-09-27 14:30 UTC, btnt51 requested changes
Исправить помеченные ошибки дедлайн до 22:30 по мск текущего дня

2021-09-27 14:30 UTC, btnt51 commented on src/Information/Parser/ToolsForParser/ArpReassembly/header/ArpReassembly.h
> +//#include <TcpReassembly.h>
Убрать эту строчку

2021-09-27 14:30 UTC, btnt51 commented on src/Information/Parser/ToolsForParser/ArpReassembly/header/ArpReassembly.h
> +        std::vector<std::string> ArpReassembler(const pcpp::Packet& packet);
Написать коментарий перд ArpReassembly о чём этот namespace

2021-09-27 14:30 UTC, btnt51 commented on src/Information/Parser/ToolsForParser/ArpReassembly/src/ArpReassembly.cpp
>      if(packet.isPacketOfType(pcpp::ARP)) {
исправить скобку в соответсвии с стиль-гайдом

2021-09-27 14:30 UTC, btnt51 commented on src/Information/Parser/ToolsForParser/ArpReassembly/header/ArpReassembly.h
> +    namespace ArpReassembly{
исправить скобку в соответсвии с стиль-гайдом

2021-09-27 14:30 UTC, btnt51 commented on src/Information/Parser/ToolsForParser/HttpReassembly/header/HttpReassembly.h
> +    namespace HttpReassembly {
исправить скобку в соответсвии с стиль-гайдом

2021-09-27 14:30 UTC, btnt51 commented on src/Information/Parser/ToolsForParser/HttpReassembly/header/HttpReassembly.h
>  namespace Information{
исправить скобку в соответсвии с стиль-гайдом

2021-09-27 14:30 UTC, btnt51 commented on src/Information/Parser/ToolsForParser/IpReassembly/header/IpReassembly.h
>      };
В этом файле исправить скобки в соотвествии с стиль гайдом, поправить комментарий, расписать подробнее об namespace IpReassembly между первым и вторым объявлением namespace

2021-09-27 14:30 UTC, btnt51 commented on src/Information/Parser/ToolsForParser/TcpReassembly/header/TcpReassembly.h
>      };
исправить скобки в соответсвии с стиль-гайдом, расписать об файле и namespace TCPReassembly

2021-09-27 14:30 UTC, btnt51 commented on src/Service/Transformer/header/Transformer.h
> +    std::string::size_type size_tToString(std::size_t size);
Произвести рефакторинг названия функции, в соотвесвтии с названиями других функций в этом файле, написать коментарий об этой функции.

2021-09-27 14:30 UTC, btnt51 commented on src/Information/Loader/header/Loader.h
>              //чтение пакетов файла. Аргументом в метод передается путь до файла
Написать комменарий в соответсвии с стиль гайду об namespace Loader и об каждой функции.

2021-09-30 08:49 UTC, btnt51 requested changes
Исправляй проблему с комментариями и точками с запятами.

2021-09-30 08:49 UTC, btnt51 commented on src/Information/Loader/src/Loader.cpp
>      //указываем ридеру, что чтение будет проходить над данным файлом
Убираем этот комментарий

2021-09-30 08:49 UTC, btnt51 commented on src/Information/Loader/src/Loader.cpp
>      reader->close(); //закрываем ридер
убираем тут коментарий

2021-09-30 08:49 UTC, btnt51 commented on src/Information/Parser/ToolsForParser/ArpReassembly/header/ArpReassembly.h
> +        std::vector<std::string> ArpReassembler(const pcpp::Packet& packet);
Оверхед вектора не 8 байт, а 24

2021-09-30 08:49 UTC, btnt51 commented on src/Information/Parser/ToolsForParser/IpReassembly/header/IpReassembly.h
>  *класса IpReassembly
ты так и не исправил с класса на namespace

2021-09-30 08:49 UTC, btnt51 commented on src/Information/Loader/src/Loader.cpp
>      //указываем ридеру, что чтение будет проходить над данным файлом
Удалить этот комментарий

2021-09-30 08:49 UTC, btnt51 commented on src/Information/Loader/src/Loader.cpp
>      reader->close(); //закрываем ридер
Удалить комментарий в данный строчке

2021-09-30 08:49 UTC, btnt51 commented on src/Information/Loader/src/Loader.cpp
>      //указываем ридеру, что чтение будет проходить над данным файлом
Удалить этот комментарий

2021-09-30 08:49 UTC, btnt51 commented on src/Information/Loader/src/Loader.cpp
>      //указываем ридеру, что чтение будет проходить над данным файлом
Удалить этот комментарий

2021-09-30 08:49 UTC, btnt51 commented on src/Information/Loader/src/Loader.cpp
>      reader->close(); //закрываем ридер
Удалить комментарий в этой строчке

2021-09-30 08:49 UTC, btnt51 commented on src/Information/Loader/src/Loader.cpp
>      //указываем ридеру, что чтение будет проходить над данным файлом
Удалить комментарий в этой строчке

2021-09-30 08:49 UTC, btnt51 commented on src/Information/Loader/src/Loader.cpp
>      reader->close(); //закрываем ридер
Удалить комментарий в этой строчке

2021-09-30 08:49 UTC, btnt51 commented on src/Information/Loader/src/Loader.cpp
>      //указываем ридеру, что чтение будет проходить над данным файлом
Удалить комментарий в этой строчке

2021-09-30 08:49 UTC, btnt51 commented on src/Information/Loader/src/Loader.cpp
>      reader->close(); //закрываем ридер
Удалить комментарий в этой строчке

2021-09-30 08:49 UTC, btnt51 commented on src/Information/Loader/src/Loader.cpp
>      reader->close(); //закрываем ридер
Удалить комментарий в этой строчке

2021-09-30 08:49 UTC, btnt51 commented on src/Information/Loader/src/Loader.cpp
>      //указываем ридеру, что чтение будет проходить над данным файлом
Удалить комментарий тут, в 36,42,43, 49 и 79 строчке

2021-09-30 08:49 UTC, btnt51 commented on src/Information/Loader/src/Loader.cpp
>      //указываем ридеру, что чтение будет проходить над данным файлом
Удалить лишние комментарии

2021-09-30 08:49 UTC, btnt51 commented on src/Information/Parser/ToolsForParser/ArpReassembly/header/ArpReassembly.h
> +     * Используемая память: 8*32 bytes(std::vector<std::string>)+ 8 bytes(overhead) +
Оверхэд у вектора 24 байта, а не 8

2021-09-30 08:49 UTC, btnt51 commented on src/Information/Parser/ToolsForParser/EthReassembly/header/EthReassembly.h
> -namespace Information{
Отсутствуют комментарии  в данном файле

2021-09-30 08:49 UTC, btnt51 commented on src/Information/Parser/ToolsForParser/HttpReassembly/header/HttpReassembly.h
> +        std::vector <std::string> HttpReassembler(pcpp::Packet packet);
Нет описания функции для документации

2021-09-30 08:49 UTC, btnt51 commented on src/Information/Parser/ToolsForParser/IpReassembly/header/IpReassembly.h
>  *класса IpReassembly
Изменить с класса на namespace

2021-09-30 08:49 UTC, btnt51 commented on src/Information/Parser/ToolsForParser/IpReassembly/header/IpReassembly.h
>      };
Убрать точку с запятой

2021-09-30 08:49 UTC, btnt51 commented on src/Information/Loader/src/Loader.cpp
>      reader->close(); //закрываем ридер
Убираем тут комментарий

2021-09-30 08:49 UTC, btnt51 commented on src/Information/Loader/src/Loader.cpp
>      //указываем ридеру, что чтение будет проходить над данным файлом
Убираем тут комментарий, а так же в 43, 44, 49 и 79 строчках

2021-09-30 08:49 UTC, btnt51 commented on src/Information/Parser/ToolsForParser/EthReassembly/header/EthReassembly.h
>      };
Убрать точку с запятой, об этом шла речь, когда говорил исправить строчки.

2021-09-30 08:49 UTC, btnt51 commented on src/Information/Parser/ToolsForParser/ArpReassembly/header/ArpReassembly.h
> +     * ArpReassembly - пространство имен, содержащий в себе функцию ArpReassembler
Не по стиль гайду

2021-09-30 08:49 UTC, btnt51 commented on src/Information/Parser/ToolsForParser/IpReassembly/header/IpReassembly.h
>  *класса IpReassembly
Исправить с класс на namespace

2021-09-30 08:49 UTC, btnt51 commented on src/Information/Parser/ToolsForParser/IpReassembly/header/IpReassembly.h
>      };
скобка так и не исправлена

2021-09-30 08:49 UTC, btnt51 commented on src/Information/Parser/ToolsForParser/TcpReassembly/header/TcpReassembly.h
>      };
Скобка не исправлена, убрать точку с запятой

2021-09-30 08:49 UTC, btnt51 commented on src/Service/Transformer/header/Transformer.h
> +     * \param[in] packet size, данные которого поместяться в тип дпнных std::string::size_type
Была задача так же описать другие функцие в этом файле

2021-09-30 08:49 UTC, btnt51 commented on src/Information/Loader/header/Loader.h
Тут проделана хорошая работа

2021-09-30 14:46 UTC, btnt51 approved these changes
Наконец-то хорошая работа, подтверждаю пуллреквест

2021-09-30 14:47 UTC, merged